//friend data list
// compare
var friendsArray = [
    {
        "name":"LaToya",
        "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/latoya.png",
        "scores":[
            3,
            4,
            1,
            5,
            3,
            3,
            2,
            1,
            4,
    ]
},  
{
    "name":"Eli",
    "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/eli.png",
    "scores":[
        3,
        5,
        1,
        4,
        5,
        1,
        2,
        5,
        4,
        1
    ]
  },

  {
    "name":"Jimmy",
    "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/jimmy.png",
    "scores":[
        2,
        1,
        1,
        2,
        5,
        4,
        2,
        3,
        4,
        1
    ]
    },
    {
        "name":"Taylor",
        "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/taylor.png",
        "scores":[
            2,
            2,
            4,
            4,
            5,
            3,
            2,
            1,
            4,
            1
        ],
    },
    {
        "name":"Roxy",
        "photo":"https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/6/005/064/1bd/roxy.jpg",
        "scores":[
            5,
            1,
            4,
            4,
            5,
            1,
            2,
            3,
            1,
            3
        ]
    }
],